title: Business Frontpage
description: A business home page starter template for Bootstrap 4 featuring marketing boxes and a full width image header.

# disabled because we are using a custom domain
url: https://rlim338.github.io/additive-indonesia.github.io/
#baseurl: /business-frontpage 

color-scheme: "#FF0000" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
