title: Additive Indonesia
description: Accelerating Additive Manufacturing Adoption in Indonesia

# disabled because we are using a custom domain
#baseurl: /business-frontpage 
url: https://rlim338.github.io/additive-indonesia.github.io/
color-scheme: "#FF0000" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
